---
title: "Dawid-Skene-anesthesia"
output: pdf_document
---

```{r setup, include=FALSE}
library(egg)
library(dplyr)
library(tidyverse)
library(here)
# helper function for string wrapping
swr <- function(string, nwrap=20) {
  paste(strwrap(string, width=nwrap), collapse="\n")
}
swr <- Vectorize(swr)

addline_format <- function(x,...){
    gsub('-','-\n',x)
}
```

Organising result into plots 
```{r}
result <- readRDS(here("Results","Dawid-Skene-result.rds"))

result$model <- factor(result$model, levels = c("stan", "jags-full", "jags-marg", "jags-full-restricted"))

result$quantity <- swr(result$quantity)
result$quantity <- factor(result$quantity, levels = c(swr("Time per min Effective Sample"), "Computation Time",swr( "Min Effective Sample Size"), "Rhat"))
result$trial <- factor(result$trial)
result$value <- as.numeric(result$value)
result
```
```{r}
plot1 <- ggplot(subset(result, quantity != "Rhat"), aes(x=model, y=value, group=model)) +  geom_boxplot() + facet_grid(quantity ~., scales='free') + theme_bw() + theme(text = element_text(size=20)) + theme(axis.title.x = element_blank()) + geom_boxplot(color="black", fill="gray", alpha=0.5) +scale_x_discrete(labels = NULL)
```

```{r}
plot2 <- ggplot(subset(result, quantity == "Rhat"), aes(x=model, y=value, group=model)) +  geom_point() + theme_bw() + facet_grid(quantity ~., scales='free') + theme(text = element_text(size=20))+geom_hline(yintercept = 1.1) + scale_x_discrete(labels=addline_format(c("stan", "jags-full", "jags-marg", "jags-full-restricted"))) 
```

```{r, fig.height=10, fig.width=5}
pdf("Dawid-Skene-result.pdf", width = 8, height = 12)
grid.arrange(plot1, plot2, ncol=1 , layout_matrix = cbind(c(1,1,1,2)))
dev.off()
```

