---
title: "three-component models"
author: "Kate Zhang"
date: "16/02/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Computation time for three-component models

```{r setting up}
require(rjags)
require(coda)
require(here)
require(rstan)
load.module("mix")
NT <- 6 # number of trials
```


```{r functions, include=FALSE}
all_sampler <- function(){
  set.factory("mix::LDA", TRUE, type="sampler")
  set.factory("mix::DirichletCat", TRUE, type="sampler")
  set.factory("bugs::BinomSlice", TRUE, type="sampler")
  set.factory("bugs::RW1", TRUE, type="sampler")
  set.factory("bugs::Censored", TRUE, type="sampler")
  set.factory("bugs::Sum", TRUE, type="sampler")
  set.factory("bugs::DSum", TRUE, type="sampler")
  set.factory("bugs::Conjugate", TRUE, type="sampler")
  set.factory("bugs::Dirichlet", TRUE, type="sampler")
  set.factory("zbugs::MNormal", TRUE, type="sampler")
  set.factory("base::Finite", TRUE, type="sampler")
  set.factory("base::Slice", TRUE, type="sampler")
  set.factory("mix::TemperedMix", TRUE, type="sampler")
}

res_sampler <- function(){
  set.factory("mix::LDA", FALSE, type="sampler")
  set.factory("mix::DirichletCat", FALSE, type="sampler")
  set.factory("bugs::BinomSlice", FALSE, type="sampler")
  set.factory("bugs::RW1", FALSE, type="sampler")
  set.factory("bugs::Censored", FALSE, type="sampler")
  set.factory("bugs::Sum", FALSE, type="sampler")
  set.factory("bugs::DSum", FALSE, type="sampler")
  set.factory("bugs::Conjugate", FALSE, type="sampler")
  set.factory("bugs::Dirichlet", TRUE, type="sampler")
  set.factory("bugs::MNormal", FALSE, type="sampler")
  set.factory("base::Finite", FALSE, type="sampler")
  set.factory("base::Slice", TRUE, type="sampler")
  set.factory("mix::TemperedMix", FALSE, type="sampler")
}




sampling <- function(datafile, result, resultr, resultstan){
  # set up
  all_sampler()
  data <- read.table(datafile)
  y <- data[,1]
  iterations <- 3000
  burnin <- floor(iterations/2)
  chains <- 3
  
  N <- nrow(data)
  data_jags <- list(N=N, y=y)
  parameters = c("mu", "sigma", "mixing_p","z")
  
   # with stan
  for(i in 1:NT){
      resultstan[1,i]<- system.time(model_fit <- stan(file =
                                    here("Models","three-componentModel.stan"), 
                        data = data_jags, iter=iterations, chain=chains,
                        warmup=burnin))["elapsed"]
      resultstan[2,i] <- min(summary(model_fit)$summary[,"n_eff"][1:6])
      resultstan[3,i] <- resultstan[1,i]/resultstan[2,i]
      
    }   
  # with unrestricted models
  
  for(j in 1:3){
    for(i in 1:NT){
      model <- paste("three-componentModel",j,".txt",sep="")
      result[j,1,i]<- system.time(model.fit <- jags.model(file =                                 here("Models",model), data=data_jags, n.chains=chains))["elapsed"]
      result[j,2,i] <- system.time(model.samples <-                                    coda.samples(model.fit, parameters,n.iter=iterations))["elapsed"]
      result[j,3,i] <- min(effectiveSize(model.samples)[0:9])
      result[j,4,i] <-   (result[j,1,i]+result[j,2,i])/result[j,3,i]                                                            
    } 
  }
  
  # with restricted models
  res_sampler()

  for(j in 1:3){
    for(i in 1:NT){
      model <- paste("three-componentModel",j,".txt",sep="")
      resultr[j,1,i]<- system.time(model.fit <- jags.model(file =                                 here("Models",model), data=data_jags, n.chains=chains))["elapsed"]
      resultr[j,2,i] <- system.time(model.samples <-                                    coda.samples(model.fit, parameters, n.iter=iterations))["elapsed"]
      resultr[j,3,i] <- min(effectiveSize(model.samples)[0:9])
      
      resultr[j,4,i] <- (resultr[j,1,i]+resultr[j,2,i])/resultr[j,3,i]                                                            
    } 
  }
  
  return(list(result=result, resultr=resultr, resultstan=resultstan))
}


```
# With data1:
N = 200
mixing_p = c(0.20, 0.50, 0.3)
mu = c(7, -12, 0)
prec = c(1, 4, 1/4)
sigma = sqrt(1/prec)
```{r data1 density, echo=FALSE}
x <- as.numeric(unlist(read.table(here("Data", "tdata1.txt"))))
plot(density(x), main="data1")
```

```{r sampling with data1, echo=FALSE, include= FALSE}
# three dimensional array for storing data
# 3 - 3 models
# 4 - 1:fit.time, 2:sample.tim, 3:ess, 4:(fit+sam)/ess
# 5 - 5 trials
result <- array(rep(0, 12*NT), dim=c(3,4,NT), 
                dimnames = list(c("m1","m2","m3"),
                                c("fit","sam","ess","res"),
                                sprintf("t%d",1:NT)))
resultr <- array(rep(0, 12*NT), dim=c(3,4,NT), 
                dimnames = list(c("m1r","m2r","m3r"),
                                c("fit","sam","ess","res"),
                                sprintf("t%d",1:NT)))
resultstan <- array(rep(0, 3*NT), dim=c(3,NT), 
                dimnames = list(c("time","ess","stan"),
                                sprintf("t%d",1:NT)))

r1 <- sampling(here("Data", "tdata1.txt"), result, resultr, resultstan)
```


```{r data1 gathering result}
data1 <- c(rowMeans(r1$result[,4,]), rowMeans(r1$resultr[,4,]),rowMeans(r1$resultstan)[3])
boxplot(t(rbind(r1$result[,4,],r1$resultr[,4,],r1$resultstan[3:3,,drop=FALSE])),main="data1")
```

# With data2:
N = 200
mixing_p = c(0.20, 0.50, 0.3)
mu = c(7, -12, 0)
prec = c(1, 4, 1/4)
sigma = sqrt(1/prec)
```{r data2 density}
x <- as.numeric(unlist(read.table(here("Data", "tdata2.txt"))))
plot(density(x), main="data2")
```

```{r sampling with data2, echo=FALSE, include= FALSE}

r2 <- sampling(here("Data", "tdata2.txt"), result, resultr, resultstan)
```

```{r data2 gathering result}
data2 <- c(rowMeans(r2$result[,4,]), rowMeans(r2$resultr[,4,]),rowMeans(r2$resultstan)[3])
boxplot(t(rbind(r2$result[,4,],r2$resultr[,4,],r2$resultstan[3:3,,drop=FALSE])),main="data2")
```

# With data3:
N = 200
mixing_p = c(0.10, 0.60, 0.3)
mu = c(9, -10, 0)
prec = c(4, 1, 6)
sigma = sqrt(1/prec)
```{r data3 density}
x <- as.numeric(unlist(read.table(here("Data", "tdata3.txt"))))
plot(density(x), main="data3")
```

```{r sampling with data3, echo=FALSE, include= FALSE}
r3 <- sampling(here("Data", "tdata3.txt"), result, resultr, resultstan)
```

```{r data3 gathering result}
data3 <- c(rowMeans(r3$result[,4,]), rowMeans(r3$resultr[,4,]),rowMeans(r3$resultstan)[3])
boxplot(t(rbind(r3$result[,4,],r3$resultr[,4,],r3$resultstan[3:3,,drop=FALSE])),main="data3")
```


# With data4:
N = 200
mixing_p = c(0.4, 0.30, 0.4)
mu = c(-1, -6, 4)
prec = c(1/3, 1/3, 1/4)
sigma = sqrt(1/prec)
```{r data4 density}
x <- as.numeric(unlist(read.table(here("Data", "tdata4.txt"))))
plot(density(x), main="data4")
```


```{r sampling with data4, echo=FALSE, include= FALSE}
r4 <- sampling(here("Data", "tdata4.txt"), result, resultr, resultstan)
```

```{r data4 gathering result}
data4 <- c(rowMeans(r4$result[,4,]), rowMeans(r4$resultr[,4,]),rowMeans(r4$resultstan)[3])
boxplot(t(rbind(r4$result[,4,],r4$resultr[,4,],r4$resultstan[3:3,,drop=FALSE])),main="data4")
```
# With data5:
N = 200
mixing_p = c(0.3, 0.50, 0.2)
mu = c(-2, -8, 4)
prec = c(1/3, 1/3, 1/4)
sigma = sqrt(1/prec)

```{r data5 density}
x <- as.numeric(unlist(read.table(here("Data", "tdata5.txt"))))
plot(density(x), main="data5")
```


```{r sampling with data5, echo=FALSE, include= FALSE}
r5 <- sampling(here("Data", "tdata5.txt"), result, resultr, resultstan)
```

```{r data5 gathering result}
data5 <- c(rowMeans(r5$result[,4,]), rowMeans(r5$resultr[,4,]),rowMeans(r5$resultstan)[3])
boxplot(t(rbind(r5$result[,4,],r5$resultr[,4,],r5$resultstan[3:3,,drop=FALSE])),main="data5")
```


```{r final graph generation, echo=FALSE}
library(ggplot2)
library(reshape2)
all_data <- matrix(c(data1,data2,data3,data4,data5), ncol=5, byrow=FALSE)
colnames(all_data) <- factor(c("data1", "data2","data3","data4","data5"))
rnames <- factor(c("m1","m2","m3","mr1","mr2","mr3", "stan"))
all_data.df <- as.data.frame(all_data)
all_data.df <- cbind(rnames, all_data.df)
m_all_data.df <- melt(all_data.df,id=c("rnames"))

ggplot(m_all_data.df, aes(x=as.numeric(rnames), y=value, col=variable))+ geom_point()+
  geom_line()+
  scale_y_log10(breaks=c(1e-3,1e-2,1e-1,0.5),limits = c(0.001,1))+
  ylab("Time per effective sample(s)")+
  xlab("models")+
  ggtitle("Computation time for the six models") +
  scale_x_continuous(labels=c("m1","m2","m3","m1r","m2r","m3r","stan"),
                     breaks=c(1,2,3,4,5,6,7))+
  theme(legend.position = "right",legend.title = element_blank(),
        panel.grid.minor = element_blank())
```

```{r final graph with m2 and m3 combined, echo=FALSE}
t_data=all_data

t_data[2,]=colMeans(rbind(all_data[2,],all_data[5,]))
t_data[3,]=colMeans(rbind(all_data[3,],all_data[6,]))
t_data[5,]=t_data[7,]
t_data = t_data[1:5,]
n_all_data = t_data
n_all_data[3,]=t_data[4,]
n_all_data[5,]=t_data[3,]
n_all_data[4,]=t_data[2,]
n_all_data[1,] = t_data[5,]
n_all_data[2,] = t_data[1,]

n_rnames <- factor(c("astan","m1","m1r","m2(r)","m3(r)"))
n_all_data.df <- as.data.frame(n_all_data)
n_all_data.df <- cbind(n_rnames, n_all_data.df)
m_n_all_data.df <- melt(n_all_data.df,id=c("n_rnames"))

ggplot(m_n_all_data.df, aes(x=as.numeric(n_rnames), y=value, col=variable))+ geom_point()+
  geom_line()+
  scale_y_log10(breaks=c(1e-3,1e-2,1e-1),limits = c(0.001,1))+
  ylab("Time per effective sample(s)")+
  xlab("models")+
  ggtitle("Computation time for four models") +
  scale_x_continuous(labels=c("stan","m1","m1r","m3(r)","m2(r)"),
                     breaks=c(1,2,3,4,5))+
  theme(legend.position = "right",legend.title = element_blank(),
        panel.grid.minor = element_blank())


```