---
title: "two-component models result"
author: "Kate Zhang"
date: "23/02/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Computation time for two-component models

```{r setting up}
require(rjags)
require(coda)
load.module("mix")
NT <- 6 # number of trials
```

```{r functions, include=FALSE}
all_sampler <- function(){
  set.factory("mix::LDA", TRUE, type="sampler")
  set.factory("mix::DirichletCat", TRUE, type="sampler")
  set.factory("bugs::BinomSlice", TRUE, type="sampler")
  set.factory("bugs::RW1", TRUE, type="sampler")
  set.factory("bugs::Censored", TRUE, type="sampler")
  set.factory("bugs::Sum", TRUE, type="sampler")
  set.factory("bugs::DSum", TRUE, type="sampler")
  set.factory("bugs::Conjugate", TRUE, type="sampler")
  set.factory("bugs::Dirichlet", TRUE, type="sampler")
  set.factory("zbugs::MNormal", TRUE, type="sampler")
  set.factory("base::Finite", TRUE, type="sampler")
  set.factory("base::Slice", TRUE, type="sampler")
  set.factory("mix::TemperedMix", TRUE, type="sampler")
}

res_sampler <- function(){
  set.factory("mix::LDA", FALSE, type="sampler")
  set.factory("mix::DirichletCat", FALSE, type="sampler")
  set.factory("bugs::BinomSlice", FALSE, type="sampler")
  set.factory("bugs::RW1", FALSE, type="sampler")
  set.factory("bugs::Censored", FALSE, type="sampler")
  set.factory("bugs::Sum", FALSE, type="sampler")
  set.factory("bugs::DSum", FALSE, type="sampler")
  set.factory("bugs::Conjugate", FALSE, type="sampler")
  set.factory("bugs::Dirichlet", TRUE, type="sampler")
  set.factory("bugs::MNormal", FALSE, type="sampler")
  set.factory("base::Finite", FALSE, type="sampler")
  set.factory("base::Slice", TRUE, type="sampler")
  set.factory("mix::TemperedMix", FALSE, type="sampler")
}




sampling <- function(datafile, result, resultr){
  # set up
  all_sampler()
  data <- read.table(datafile)
  y <- data[,1]
  iterations <- 3000
  burnin <- floor(iterations/2)
  chains <- 2
  
  N <- nrow(data)
  data_jags <- list(N=N, y=y)
  parameters = c("mu", "sigma", "mixing_p","z")
  
  # with unrestricted models
  
  for(j in 1:3){
    for(i in 1:NT){
      model <- paste("two-componentModel",j,".txt",sep="")
      result[j,1,i]<- system.time(model.fit <- jags.model(file =                                 model, data=data_jags, n.chains=chains))["elapsed"]
      result[j,2,i] <- system.time(model.samples <-                                    coda.samples(model.fit, parameters,n.iter=iterations))["elapsed"]
      result[j,3,i] <- min(effectiveSize(model.samples)[0:6])
      result[j,4,i] <-   (result[j,1,i]+result[j,2,i])/result[j,3,i]                                                            
    } 
  }
  
  # with restricted models
  res_sampler()

  for(j in 1:3){
    for(i in 1:NT){
      model <- paste("two-componentModel",j,".txt",sep="")
      resultr[j,1,i]<- system.time(model.fit <- jags.model(file =                                 model, data=data_jags, n.chains=chains))["elapsed"]
      resultr[j,2,i] <- system.time(model.samples <-                                    coda.samples(model.fit, parameters, n.iter=iterations))["elapsed"]
      resultr[j,3,i] <- min(effectiveSize(model.samples)[0:6])
      
      resultr[j,4,i] <- (resultr[j,1,i]+resultr[j,2,i])/resultr[j,3,i]                                                            
    } 
  }
  
  return(list(result=result, resultr=resultr))
}


```

# With data1:
N = 350
mixing_p = c(0.20, 0.80)
mu = c(10, -2)
prec = c(1/4, 1/25)
sigma = sqrt(1/prec)
```{r data1 density, echo=FALSE}
x <- as.numeric(unlist(read.table("data2.txt")))
plot(density(x), main="data1")
```

```{r sampling with data1, echo=FALSE, include= FALSE}
# three dimensional array for storing data
# 3 - 3 models
# 4 - 1:fit.time, 2:sample.tim, 3:ess, 4:(fit+sam)/ess
# 5 - 5 trials
result <- array(rep(0, 12*NT), dim=c(3,4,NT), 
                dimnames = list(c("m1","m2","m3"),
                                c("fit","sam","ess","res"),
                                sprintf("t%d",1:NT)))
resultr <- array(rep(0, 12*NT), dim=c(3,4,NT), 
                dimnames = list(c("m1r","m2r","m3r"),
                                c("fit","sam","ess","res"),
                                sprintf("t%d",1:NT)))

r1 <- sampling("data2.txt", result, resultr)
```


```{r data1 gathering result}
data1 <- c(rowMeans(r1$result[,4,]), rowMeans(r1$resultr[,4,]))
boxplot(t(rbind(r1$result[,4,],r1$resultr[,4,])),main="data1")
```

# With data2:
N = 800
mixing_p = c(0.60, 0.40)
mu = c(0, -1)
prec = c(9, 4)
sigma = sqrt(1/prec)
```{r data2 density}
x <- as.numeric(unlist(read.table("data3.txt")))
plot(density(x), main="data2")
```

```{r sampling with data2, echo=FALSE, include= FALSE}

r2 <- sampling("data3.txt", result, resultr)
```

```{r data2 gathering result}
data2 <- c(rowMeans(r2$result[,4,]), rowMeans(r2$resultr[,4,]))
boxplot(t(rbind(r2$result[,4,],r2$resultr[,4,])),main="data2")
```

# With data3:
N = 350
mixing_p = c(0.30, 0.7)
mu = c(8, -10)
prec = c(1/9, 1/4)
sigma = sqrt(1/prec)
```{r data3 density}
x <- as.numeric(unlist(read.table("data4.txt")))
plot(density(x), main="data3")
```

```{r sampling with data3, echo=FALSE, include= FALSE}
r3 <- sampling("data4.txt", result, resultr)
```

```{r data3 gathering result}
data3 <- c(rowMeans(r3$result[,4,]), rowMeans(r3$resultr[,4,]))
boxplot(t(rbind(r3$result[,4,],r3$resultr[,4,])),main="data3")
```

# With data4:
N = 950
mixing_p = c(0.50, 0.50)
mu = c(10, -10)
prec = c(1/81, 1/64)
sigma = sqrt(1/prec)
```{r data4 density}
x <- as.numeric(unlist(read.table("data5.txt")))
plot(density(x), main="data4")
```

```{r sampling with data4, echo=FALSE, include= FALSE}
r4 <- sampling("data5.txt", result, resultr)
```

```{r data4 gathering result}
data4 <- c(rowMeans(r4$result[,4,]), rowMeans(r4$resultr[,4,]))
boxplot(t(rbind(r4$result[,4,],r4$resultr[,4,])),main="data4")
```

# With data5:
N = 350
mixing_p = c(0.40, 0.60)
mu = c(7, -12)
prec = c(1, 4)
sigma = sqrt(1/prec)
```{r data5 density}
x <- as.numeric(unlist(read.table("data6.txt")))
plot(density(x), main="data5")
```

```{r sampling with data5, echo=FALSE, include= FALSE}
r5 <- sampling("data6.txt", result, resultr)
```

```{r data5 gathering result}
data5 <- c(rowMeans(r5$result[,4,]), rowMeans(r5$resultr[,4,]))
boxplot(t(rbind(r5$result[,4,],r5$resultr[,4,])),main="data5")
```


```{r final graph generation, echo=FALSE}
library(ggplot2)
library(reshape2)
all_data <- matrix(c(data1,data2,data3,data4,data5), ncol=5, byrow=FALSE)
colnames(all_data) <- factor(c("data1", "data2","data3","data4","data5"))
rnames <- factor(c("m1","m2","m3","mr1","mr2","mr3"))
all_data.df <- as.data.frame(all_data)
all_data.df <- cbind(rnames, all_data.df)
m_all_data.df <- melt(all_data.df,id=c("rnames"))

ggplot(m_all_data.df, aes(x=as.numeric(rnames), y=value, col=variable))+ geom_point()+
  geom_line()+
  scale_y_log10(breaks=c(1e-3,1e-2,1e-1,0.5,2.5),limits = c(0.001,2.5))+
  ylab("Time per effective sample(s)")+
  xlab("models")+
  ggtitle("Computation time for the six models") +
  scale_x_continuous(labels=c("m1","m2","m3","m1r","m2r","m3r"),
                     breaks=c(1,2,3,4,5,6))+
  theme(legend.position = "right",legend.title = element_blank(),
        panel.grid.minor = element_blank())
```
```{r final graph with m2 and m3 combined, echo=FALSE}
t_data=all_data

t_data[2,]=colMeans(rbind(all_data[2,],all_data[5,]))
t_data[3,]=colMeans(rbind(all_data[3,],all_data[6,]))
t_data = t_data[1:4,]
n_all_data = t_data
n_all_data[2,]=t_data[4,]
n_all_data[4,]=t_data[3,]
n_all_data[3,]=t_data[2,]


n_rnames <- factor(c("m1","m1r","m2(r)","m3(r)"))
n_all_data.df <- as.data.frame(n_all_data)
n_all_data.df <- cbind(n_rnames, n_all_data.df)
m_n_all_data.df <- melt(n_all_data.df,id=c("n_rnames"))

ggplot(m_n_all_data.df, aes(x=as.numeric(n_rnames), y=value, col=variable))+ geom_point()+
  geom_line()+
  scale_y_log10(breaks=c(1e-3,1e-2,1e-1,2.5),limits = c(0.001,2.5))+
  ylab("Time per effective sample(s)")+
  xlab("models")+
  ggtitle("Computation time for four models") +
  scale_x_continuous(labels=c("m1","m1r","m2(r)","m3(r)"),
                     breaks=c(1,2,3,4))+
  theme(legend.position = "right",legend.title = element_blank(),
        panel.grid.minor = element_blank())


```